apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-resource-operator
  labels:
    type: operator
    service: client-resource-operator
    language: java
spec:
  replicas: 1
  selector:
    matchLabels:
      type: operator
      service: client-resource-operator
  template:
    metadata:
      labels:
        type: operator
        service: client-resource-operator
        language: java
    spec:
      containers:
        - name: client-resource-operator
          image: olgafedorova/k8s-operator-java-example:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: client-resource-operator
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    type: operator
    service: client-resource-operator

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-resource-operator
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/clients
            backend:
              serviceName: client-resource-operator
              servicePort: 8080
